In [1]:
import numpy as np

##### Basics

In [3]:
# creating an one-dimensional array

a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [4]:
# creating a two-dimensional array

b = np.array([[1, 2, 3], [4, 5, 6]], dtype='int32')
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# get dimension

print(a.ndim)
print(b.ndim)

1
2


In [8]:
# get shape

print(b.shape)

(2, 3)


In [10]:
# get type

print(a.dtype)

int32


In [12]:
# get element size

print(a.itemsize)

4


In [14]:
# get number of elements

print(b.size)

6


In [15]:
# get total size

print(b.nbytes)

24


##### accessing, modifying specific elements, rows, columns..

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# access specifi element [r, c]
print(a[1, 3])

11


In [22]:
# accessing a specific row

print(a[1, :])

[ 8  9 10 11 12 13 14]


In [25]:
# accessing a specific column

print(a[:, 1])

[2 9]


In [27]:
# slicing works same as it works in python [start : end : step]
# negative numbers are also supported, same as in python

print(a[0, 1:6:2])

[2 4 6]


In [29]:
# modifying an element

a[1, 3] = 25        # btw, 25 is shikhar dhawan's old jersey number 

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 25 12 13 14]]


In [30]:
# an example of 3d array

b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [1, 2, 3]]])
print(b)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [32]:
# access in 3d array - think outside in (watch youtube video for clarity)

print(b[1, 1, 2])

3


In [35]:
# replacing in 3d array

b[:, 1, :] = [[1, 2, 3], [4, 5, 6]]
print(b)

[[[1 2 3]
  [1 2 3]]

 [[7 8 9]
  [4 5 6]]]


##### Initializing Different Types of Arrays

In [36]:
# all 0s matrix

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# all 1s matrix

np.ones((2, 3, 4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [43]:
# all x's matrix

np.full((3, 2, 2), 25)

array([[[25, 25],
        [25, 25]],

       [[25, 25],
        [25, 25]],

       [[25, 25],
        [25, 25]]])

In [46]:
# using full_like, instead of using custom dimensions, we can use an array

np.full_like(b, 25)

array([[[25, 25, 25],
        [25, 25, 25]],

       [[25, 25, 25],
        [25, 25, 25]]])

In [48]:
# using random, by default it will generate random decimals

np.random.rand(3, 8)

array([[0.42098698, 0.67410901, 0.84553127, 0.09340382, 0.79428246,
        0.47323536, 0.86599275, 0.44575119],
       [0.16094092, 0.69723276, 0.23909815, 0.27868217, 0.57595025,
        0.53630535, 0.90764462, 0.80554988],
       [0.92535626, 0.10360145, 0.54821329, 0.1681624 , 0.96498701,
        0.01470948, 0.04594754, 0.96300011]])

In [51]:
# generating array with random integers

np.random.randint(18, 25, size=(2, 3))

# np.random.randint(start, end + 1, size=(rows, cols))

array([[21, 19, 21],
       [19, 18, 21]], dtype=int32)

In [53]:
# generating identity matrix

np.identity(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [57]:
# repeating an array

nums = np.array([[1, 2, 3]])

new = np.repeat(nums, 3, axis=0)
print(new)

new = np.repeat(nums, 3, axis=1)
print(new)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [58]:
# copying arrays

a = np.array([1, 2, 3])

b = a
b[0] = 100

print(a)
print(b)

a = np.array([1, 2, 3])

b = a.copy()
b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


##### maths

In [59]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [60]:
a + 2

array([3, 4, 5, 6, 7])

In [61]:
a - 2

array([-1,  0,  1,  2,  3])

In [63]:
a * 2

array([ 2,  4,  6,  8, 10])

In [64]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [65]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [67]:
b = np.array([6, 7, 8, 9, 0])
a + b

array([ 7,  9, 11, 13,  5])

In [68]:
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [69]:
print(np.sin(a) ** 2 + np.cos(a) ** 2)

[1. 1. 1. 1. 1.]


In [ ]:
# resources for advanced math commands/utilities/syntax

# (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [71]:
a = np.ones((3, 2))
print(a)

b = np.full((2, 3), 2)
print(b)

c = np.matmul(a, b)
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [73]:
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [75]:
# resources for advanced linear algebra commands/utilities/syntax

# (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

##### statistics

In [76]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [77]:
print(np.min(a))
print(np.max(a))

1
8


In [78]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [79]:
np.min(a, axis=1)

array([1, 5])

In [81]:
print(np.sum(a))
print(np.mean(a))

36
4.5


In [82]:
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[ 6  8 10 12]
[10 26]


##### reorganizing arrays

In [83]:
before = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2]])
print(before)

after = before.reshape((6, 2))
print(after)

[[1 2 3 4 5 6]
 [7 8 9 0 1 2]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]
 [1 2]]


In [84]:
# vertically stacking vectors

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.vstack([a, b, a, b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# horizontal stacking of vectors

a = np.full((3, 4), 18)
b = np.full((3, 2), 25)

np.hstack([a, b])

array([[18, 18, 18, 18, 25, 25],
       [18, 18, 18, 18, 25, 25],
       [18, 18, 18, 18, 25, 25]])

##### miscellaneous

In [93]:
# loading data from a txt/csv file.

data = np.genfromtxt('data.txt', delimiter=',')
data = data.astype('int32')
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [94]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])